Feature/karpunov/dp 6 main screen
DavayPosmotrim/dv-iOS pull request #14
Opened 2024-04-30 09:56 UTC by IuriiKarpunov

2024-05-01 10:31 UTC, uistelmakh commented on DavaiPosmotrim/MainFlow/MainCoordinator.swift
> +        case "AuthViewController":
строки лучше вынеси в константы

2024-05-01 11:44 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +    }()
Тут точно не должно быть private?

2024-05-01 12:05 UTC, superaydumov requested changes

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +    lazy var titleLabel: UILabel = {
Тут точно не должно быть private?

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +            mainViewController.navigateTo(screen: "JoinSessionViewController")
Эти строки лучше вынести в отдельную структуру на мой взгляд

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +        label.font = UIFont(name: "DaysOne-Regular", size: 16)
У нас есть расширение для UIFont в папке Helpers.
Оттуда можно взять уже занесенные шрифты: 
.textLabelFont - для этого случая, к примеру.

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    lazy var descriptionLabel: UILabel = {
Точно не должен быть private?

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        label.font = UIFont(name: "Inter-Regular", size: 12)
Шрифт из расширения для UIFont: .textCaptionRegularFont

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +
Лишний отступ

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        label.font = UIFont(name: "DaysOne-Regular", size: 16)
Шрифт из расширения для UIFont: .textLabelFont

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        navigateTo(screen: "AuthViewController")
Лучше перенести в отдельную структуру со строками, как писал выше))

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        return 3
Просто в качестве идеи: Может создать отдельную структуру с параметрами, которые ты будешь передавать в ячейку (модель для ячейки грубо говоря)? И уже во вьюконтроллере создать массив этих моделей, чтобы использовать что-то вроде modelsArray.count в этом месте.

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +            mainTableViewCell.configureCell(
И тут получается, что метод будет принимать тип твоей созданной модели для ячейки. Не нужно будет кучу параметров передавать, а только модель)) и через нее дотягиваться до нужных свойств будешь. Сократишь код, читаться легче будет..

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +
Лишний отступ

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewProtocol.swift
> +    // Пустое расширение без реализации методов делегата
Может лучше добавить TODO, чтобы, на всякий случай, не забыть это сделать?

2024-05-01 12:05 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // Пустое расширение без реализации методов делегата
Может лучше добавить TODO, чтобы, на всякий случай, не забыть это сделать?

2024-05-01 13:37 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +    lazy var titleLabel: UILabel = {
Должен быть)

2024-05-01 14:43 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +            mainViewController.navigateTo(screen: "CreateSessionViewController")
Мне кажется, что при MVP + C - вью не должно знать что мы хотим показать какой-то экран. Вью должно сообщить презентеру о том, что нажата такая то кнопка. У нас же тут получается, что вью отвечает за навигацию, а это не совсем верно по-моему мнению.

2024-05-01 14:46 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    Забудьте о бесконечных спорах и компромиссах
А мы не будем делать для строк файл localize? Просто это было бы удобнее точно. Но надо обсудить.

2024-05-01 14:50 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainSceneFactory.swift
> +    static func makeMainViewController(with coordinator: MainCoordinator) -> MainViewController {
Надо обсудить по поводу координаторов: будем ли мы закрывать их протоколами, или нет. По хорошему, как мне кажется - надо.

2024-05-01 14:54 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainPresenterProtocol.swift
> +        coordinator.showNextScreen(screen: screen)
А если финиш вызывать уже в showNextScreen в координаторе? Не уверен, но мне кажется так будет более правильно? А то тут получается, что мы сначала координатору говорим, что пора завершать работу, а потом опять просим его поработать.

2024-05-01 15:00 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // MARK: - IBAction
У нас нет марки IBAction, судя по ридми... более того, насколько я помню, IBAction - обычно подразумевает работу с сторибордом. (могу быть не прав). Давайте обсудим как мы будем именовать марку с экшенами, которые приходят от UI.

2024-05-01 15:03 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        navigateTo(screen: "AuthViewController")
Я бы вообще предложил через Enum сделать, что случайно не ошибиться где-то.

2024-05-01 15:07 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainPresenterProtocol.swift
> +//  MainPresenterProtocol.swift
Я понимаю, что ты делал по примеру онбординга, но я там ошибся и назвал файл презентера как презентерПротокол. Давайте разделим все же протокол и презентер в разные файлы. и назовем правильно их.

2024-05-01 15:21 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainCoordinator.swift
> +        navigationController.pushViewController(viewController, animated: true)
Мне кажется тут надо вообще обнулить стек навигации (установить viewController как единственный в стеке, иначе мы получаем кнопку back там, где она не нужна)
![Снимок экрана 2024-05-01 в 23 21 33](https://github.com/DavayPosmotrim/dv-iOS/assets/103517615/db275123-7ce6-4373-a72f-3314ffc1e5bf)

2024-05-01 15:41 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // MARK: - IBAction
Мне кажется, что можно их "Handlers" называть

2024-05-01 18:09 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // MARK: - IBAction
да, марка такого у нас нет, но логически я бы выделял их от остальных методов

2024-05-01 18:15 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // Пустое расширение без реализации методов делегата
а, тут ничего не нужно, методы в ячейке без него не работают, лучше extension уберу

2024-05-01 19:09 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    Забудьте о бесконечных спорах и компромиссах
нужно будет обсудить

2024-05-01 19:34 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +            mainViewController.navigateTo(screen: "CreateSessionViewController")
но вью и не отвечает за навигацию, она передает параметр в метод, который находится в презент MainPresenter, только в данном случае это делается через mainViewController, так как там тоже отдельная кнопка есть, не относящаяся к таблице, но использующая тот же функционал.
по факту он говорит какая кнопка была нажата

2024-05-02 01:58 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +            mainViewController.navigateTo(screen: "CreateSessionViewController")
Я все же за то, чтобы просто переиминовать метод: nameButtonPressed() или что-то в таком роде. Логика такая:
Если у тебя вью выступает делегатом ячейки, ячейка просто говорит что была нажата. Дальше вью говорит презентеру, что нажата такая то ячейка, а презентер уже думат что с этим сделано. У нас сейчас получается, что мы сразу видим, что это будет навигация. А это не совсем верно, насколько я понимаю.

2024-05-02 01:59 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    // MARK: - IBAction
Да, я тоже за то, чтобы отделять, просто IB - подразумевает Interface builder, а тут его нет :) Можнт просто Actions?

2024-05-02 13:16 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +    static let reuseIdentifier = "MainTableViewCell"
Можно тоже в структуру переместить в таком случае

2024-05-02 13:21 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainCellModel.swift
> +let mainCellModels: [MainCellModel] = [
когда комментарий писал, идея была в том, что ты создашь этот массив во вьюконтроллере (плюс в том, что он будет приватный) и будешь использовать его оттуда. В функцию configureCell будешь передавать только экземпляр модели MainCellModel, чтобы было меньше передаваемых параметров в функцию. А в самой функции внутри класса ячейки будешь использовать уже как mainCellModel.title, mainCellModel.textColor и тд

2024-05-02 13:40 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainTableViewCell.swift
> +    func configureCell(
Я имел ввиду, что в этом месте функция принимает только MainCellModel:

func configureCell(model: MainCellModel) {
titleLabel.text = model.titleLabelText
...
}

2024-05-02 16:10 UTC, superaydumov approved these changes
С моей стороны замечаний нет!))

2024-05-04 11:41 UTC, Sbat2000 approved these changes
Красавчик, брат!

2024-05-05 10:33 UTC, merged