Feature/kemenov/dp-2-setup-cicd PR
DavayPosmotrim/dv-iOS pull request #15
Opened 2024-05-02 18:13 UTC by SKemenov

- Влил файлы конфигурации fastlane в папку `./fastlane`
- Влил файлы конфигурации GitHub Actions в папку `./.github/workflows`
- Запуск fastlane локально отрабатывает, сборка собирается без ошибок:

[21:08:19]: ▸ Test build Succeeded

| Step | Action | Time (in s) |
| --- | --- | --- |
| 1    | default_platform | 0           |
| 2    | scan             | 9           |

[21:08:19]: fastlane.tools finished successfully 🎉

2024-05-02 19:39 UTC, superaydumov requested changes

2024-05-02 19:39 UTC, superaydumov commented on .github/workflows/gha-pr-dev.yml
> +      - 'bugfixe/**'
Мне кажется, что тут опечатка. Проверь пожалуйста

2024-05-03 06:39 UTC, SKemenov commented on .github/workflows/gha-pr-dev.yml
> +      - 'bugfixe/**'
Исправил

2024-05-03 07:21 UTC, superaydumov approved these changes

2024-05-03 14:39 UTC, IuriiKarpunov approved these changes
Опечаток нет, файлы выглядят хорошо структурированными

2024-05-03 14:48 UTC, merged