Feature/aidumov/dp 4 registration screen
DavayPosmotrim/dv-iOS pull request #16
Opened 2024-05-04 21:52 UTC by superaydumov

PR по выполненной задаче DP-4 по созданию экрана регистрации пользователя.
Добавлен координатор для управления навигацией.

2024-05-05 13:10 UTC, SKemenov requested changes
ИМХО излишни усложнил работу с клавиатурой, попробуй обойтись без observer.
Часть логики осталась в VC, стоит перенести её в презентер.
В паиарке внизу висит ворнинг, что есть конфликт с дев. Не забывай мерджить к себе дев, перед тем как делать пиарку.

И надо согласовать с Заказчиком:
- допустим ли ввод пробела и символов
- нажатие Ввод на клавиатуре обрабатываем или нет

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +    func showAuthentification() {
Ошибка нейминга - пустая строка после `extension`

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthPresenter.swift
> +}
Протоколы в отдельном файле или в одном? `AuthViewProtocol` в отдельном, а `AuthPresenterProtocol` в том же... 🤷🏻‍♂️

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        static let lowerLabelLengthWarhingText = "Минимум две буквы"
Опечатка

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        textField.becomeFirstResponder()
Если `textField.becomeFirstResponder()` запустить в `viewDidLoad`, то клавиатура сама появится и не нужен будет NotificationObserver

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        [upperLabel,
В этом случае скобка массива `[` на пустой строке

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        lowerLabelHeightAnchor.constant = .zero
попробуй как альтернативу: `lowerLabel.isHidden = true`

Но решать это должен презентер

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    }
Решать что показывать и как показывать - это функция презентера

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        }
Это функция презентера

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        DispatchQueue.main.async {
Почему сюда не передается Имя пользователя?
То что пока некуда его передавать - не основание не принести его сюда )

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    private var lowerLabelHeightAnchor = NSLayoutConstraint()
Рекомендую сделать переменную для хранения имени пользователя. При вводе использовать его как текущее состояние имени, при нажатии кнопки - использовать его как финальное имя для передачи на следующий экран. 
Тогда этот VC можно сделать переиспользуемым - в инит передавать имя для его редактирования (для флоу редактирования имени) или по дефолту использовать пустую строку

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        let currentstring = (nameTextField.text ?? "") as NSString
Зачем тут `NSString`?

И еще тут опечатка

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        if updatedString.rangeOfCharacter(from: CharacterSet.decimalDigits) != nil {
Нужно добавить проверку на наличие пробела и символов ИЛИ показывать другой ворнинг, не "Только буквы"

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +extension AuthViewController: UITextFieldDelegate {
Если нужно чтобы нажатие на клавиатуре было идентично нажатию экранной кнопки "войти", тогда нужно добавить еще одну функцию делегата
```swift
func textFieldShouldReturn(_ textField: UITextField) -> Bool { }
```

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewProtocol.swift
> +    // TODO: - add code to use viewControllers method in presenter
Логично в протокол добавить функции `Показать ворнинг`, `Скрыть ворнинг`

2024-05-05 13:10 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    @objc func enterButtonDidTap(sender: AnyObject) {
Это функция презентера

2024-05-05 21:44 UTC, superaydumov commented
Отвечаю на главный коммент:
Метод с наблюдателем сделан для того, чтобы кнопка войти, нижний отступ которой привязан к верху клавиатуры, знала, что клавиатура появится и привязалась к ней. Так выходит более универсальный метод для всех размеров экранов, где не приходится задавать размеры для каждого случая.

Перед отправкой на проверку, я влил ветку develop в свою (выше запись об этом есть). После создания моего PR были влиты изменения связанные с главным экраном. Отсюда и предупреждение о конфликте.

Вопросы для заказчика вынесены в таблицу.

2024-05-05 21:48 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +    func showAuthentification() {
Fixed

2024-05-05 21:48 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthPresenter.swift
> +}
Согласен. Вынес в отдельный файл

2024-05-05 21:53 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        static let lowerLabelLengthWarhingText = "Минимум две буквы"
Fixed

2024-05-05 21:57 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        textField.becomeFirstResponder()
Если убрать observer, то кнопку "войти" необходимо будет привязывать вручную.
Сейчас это происходит автоматически при сигнале на появление от клавиатуры.
becomeFirstResponder() просто нам её показывает. Находясь внутри ленивого свойства, он по сути тоже активируется при построении экрана авторизации.

2024-05-05 22:04 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        [upperLabel,
Fixed for AuthViewController, OnboardingViewController and OnboardingCollectionViewCell

2024-05-05 22:28 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        let currentstring = (nameTextField.text ?? "") as NSString
Опечатку исправил.

NSString тут потому, что мы пользуемся методом replacingCharacters(in:with:), который работает только с типом NSString. Иначе нужно конвертировать String в NSString.

2024-05-05 22:46 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        lowerLabelHeightAnchor.constant = .zero
Изменил логику работы появления lowerLabel.
Убрал лишнее свойство lowerLabelHeightAnchor

2024-05-05 23:37 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    private var lowerLabelHeightAnchor = NSLayoutConstraint()
Планировал позже это сделать, но ладно.
Добавил свойство для имени пользователя, обновил инициализатор.

2024-05-05 23:56 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        if updatedString.rangeOfCharacter(from: CharacterSet.decimalDigits) != nil {
Fixed

2024-05-06 00:05 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +extension AuthViewController: UITextFieldDelegate {
Добавил, но подождем что скажет заказчик.

2024-05-06 00:23 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    @objc func enterButtonDidTap(sender: AnyObject) {
Не совсем понял
Как экшен кнопки вьюконтроллера может быть функцией презентера?

2024-05-06 00:25 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        DispatchQueue.main.async {
Fixed

2024-05-06 03:11 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewProtocol.swift
> +    // TODO: - add code to use viewControllers method in presenter
Заменил функции на updateUIElements

2024-05-06 04:17 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        }
Перенес функцию в презентер

2024-05-06 14:24 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +extension AuthViewController: UITextFieldDelegate {
Заказчик сказал, что было бы неплохо иметь такой функционал

2024-05-06 14:25 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +        textField.becomeFirstResponder()
Изменил код по твоему совету с textField.inputAccessoryView = enterButton.
Удалил логику с observer

2024-05-07 14:09 UTC, Sbat2000 commented on DavaiPosmotrim/AuthFLow/AuthSceneFactory.swift
> +        let savedUserName = UserDefaults.standard.string(forKey: "userName") ?? ""
Я бы проверял имя в презентере после загрузки View, по мне так это более логично.

2024-05-07 14:13 UTC, Sbat2000 commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +        navigationController.pushViewController(viewController, animated: true)
Вот тут надо понять стоит ли нам пушить в текущий стек навигации или лучше обнулить его и туда рутом поставить только наш ВК авторизации? мне кажется второй вариант лучше, так как мы не должны дать пользователю нажать назад? а значит нам не нужны старые контроллеры (онбординг) в стеке.

2024-05-07 14:31 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +extension AuthViewController: UITextFieldDelegate {
Классно, что сделал!

2024-05-07 14:33 UTC, SKemenov commented on DavaiPosmotrim/AuthFLow/AuthViewController.swift
> +    @objc func enterButtonDidTap(sender: AnyObject) {
По аналоги с методом updateUIElement

2024-05-07 14:37 UTC, SKemenov approved these changes
Классно, что смог упростить код. Отличная идея с `Resources` 👍

2024-05-08 14:55 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthSceneFactory.swift
> +        let savedUserName = UserDefaults.standard.string(forKey: "userName") ?? ""
Добавил в презентер функцию по проверке сохраненного имени.
Вызов происходит в этом месте перед передачей имени во вьюконтроллер.

2024-05-08 15:02 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +        navigationController.pushViewController(viewController, animated: true)
Согласен))
Использовал `navigationController.setViewControllers([viewController], animated: true)` для обнуления стека навигации и назначения вьюконтроллера авторизации корневым

2024-05-10 03:49 UTC, Sbat2000 commented on DavaiPosmotrim/AuthFLow/AuthSceneFactory.swift
> +        let savedUserName = UserDefaults.standard.string(forKey: "userName") ?? ""
Привет! я имел ввиду чуть другое: координатор по идее не должен вообще ничего знать об имени. Я вижу логику так: наше вью загружается, говорит презентеру, что оно загружено, презентер в этот момент должен провреить имя в ЮД и отдать его вьюконтроллеру. Или ничего не отдать, если его нет.

2024-05-10 03:50 UTC, Sbat2000 approved these changes

2024-05-10 15:45 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthSceneFactory.swift
> +        let savedUserName = UserDefaults.standard.string(forKey: "userName") ?? ""
Fixed
Перенес логику вызова сохраненного имени в AuthViewController

2024-05-13 19:10 UTC, uistelmakh commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        addChild(authCoordinator)
не нужна объект создавать authCoordinator. Сразу добавляй
addChild(
           AuthCoordinator(
            type: .auth,
            finishDelegate: self,
            navigationController: navigationController
            )
         )

2024-05-13 19:13 UTC, uistelmakh commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +
лишний отступ, в экстеншне тоже

2024-05-13 19:21 UTC, uistelmakh commented on DavaiPosmotrim/AuthFLow/AuthPresenter.swift
> +            DispatchQueue.main.async {
в презентере не обновляй UI. Отображением занимается View слой

2024-05-14 08:33 UTC, superaydumov commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        addChild(authCoordinator)
А как мне тогда его стартовать?
Сейчас запускается так: authCoordinator.start()

2024-05-14 08:37 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthCoordinator.swift
> +
Fixed.
Также исправил отступы в файле Readme этой ветки.

2024-05-14 11:14 UTC, uistelmakh commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        addChild(authCoordinator)
а все окей

2024-05-14 14:12 UTC, superaydumov commented on DavaiPosmotrim/AuthFLow/AuthPresenter.swift
> +            DispatchQueue.main.async {
Fixed

2024-05-14 15:46 UTC, merged