Feature/kemenov/dp-10-mistakes-no-internet PR
DavayPosmotrim/dv-iOS pull request #17
Opened 2024-05-05 18:53 UTC by SKemenov

- Сделал кастомный элемент `RoundedButton` с возможностью настройки через `configure(title: String, type: ButtonType)`
- Сделал статичные свойства для наименования отступов, высоты строк, кнопок, плейсхолдера
- Сделал выделенный файл `Resources` для строковых переменных
- Сделал универсальный `MistakesViewController(type: MistakeType)`, чтобы из вызова сразу выбирать какой экран ошибки показывать
- В `MistakesViewController` в методах обработки нажатия кнопок стоят загрушки
- Смерджил дев перед пиаркой

closed #10

2024-05-06 15:07 UTC, superaydumov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +final class RoundedButton: UIButton {
На самом деле у нас уже есть один класс для кастомных кнопок (CustomButtons). Я использовал в онбординге эту кнопку. Она идентична с твоей.

2024-05-06 15:16 UTC, superaydumov commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        let authViewController = MistakesViewController(type: .oldVersion)
Думаешь стоит оставить? Может убрать, чтобы не было конфликта потом?

2024-05-06 15:17 UTC, superaydumov commented on DavaiPosmotrim/Helpers/CGFloat+Extensions.swift
> +}
Нужно добавить отступ

2024-05-06 15:17 UTC, superaydumov commented on DavaiPosmotrim/Mistakes/MistakesViewController.swift
> +}
Нужно добавить отступ

2024-05-06 15:18 UTC, superaydumov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +    func setupButton() {
Нужно добавить отступ

2024-05-06 15:18 UTC, superaydumov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +}
Нужно добавить отступ в соответствии с правилами.

2024-05-06 15:20 UTC, superaydumov requested changes
Единственный и большой вопрос по сути по дублированию классов для отрисовки кнопки.

2024-05-07 14:54 UTC, SKemenov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +final class RoundedButton: UIButton {
У нас разная реализация. 
Ты сделал класс UIView, а внутри уже UIButton как свойство.
Я сделал класс UIButton, что позволило сократить код. И добавил реакцию на нажатие - Заказчик сделал для этого разные цвета кнопки.

2024-05-07 14:54 UTC, SKemenov commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        let authViewController = MistakesViewController(type: .oldVersion)
убрал

2024-05-07 14:55 UTC, SKemenov commented on DavaiPosmotrim/Helpers/CGFloat+Extensions.swift
> +}
исправил

2024-05-07 14:56 UTC, SKemenov commented on DavaiPosmotrim/Mistakes/MistakesViewController.swift
> +}
исправил

2024-05-07 14:56 UTC, SKemenov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +    func setupButton() {
исправил

2024-05-07 14:57 UTC, SKemenov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +}
исправил

2024-05-07 15:04 UTC, SKemenov commented
Про дублирование кастомных классов кнопки предлагаю выносить решение на лида. Пусть Сергей решит.

2024-05-07 15:16 UTC, superaydumov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +final class RoundedButton: UIButton {
Всё верно, разная))
С нажатием согласен..но добавить в уже имеющийся CustomButtons класс эту реализацию тоже можно (по аналогии с тем, что есть в твоем классе).
CustomButtons подразумевался как место, куда мы будем складывать разные кнопки, поэтому он имеет такую структуру, а так нужно будет создавать отдельный класс на каждую кнопку
<img width="1512" alt="Снимок экрана 2024-05-07 в 18 15 23" src="https://github.com/DavayPosmotrim/dv-iOS/assets/131291379/090914e5-4037-4810-9da9-66df8296c6b8">

2024-05-07 15:18 UTC, superaydumov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +final class RoundedButton: UIButton {
Можно на обсуждение ребятам вынести и Сергею)) Поддерживаю!

2024-05-08 20:25 UTC, IuriiKarpunov approved these changes
Код выглядит вполне логичным и хорошо организованным

2024-05-10 03:53 UTC, Sbat2000 approved these changes

2024-05-10 03:54 UTC, Sbat2000 approved these changes

2024-05-13 19:56 UTC, uistelmakh commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        let authViewController = MistakesViewController(type: .oldVersion)
переменную можно не создавать. Сэть сразу  navigationController.setViewControllers([MistakesViewController(type: .oldVersion)], animated: true)

2024-05-13 19:58 UTC, uistelmakh commented on DavaiPosmotrim/UI/RoundedButton.swift
> +        self.alpha = 0.7
Создай енам с константами в классе и там храни значение

2024-05-13 19:58 UTC, uistelmakh commented on DavaiPosmotrim/UI/RoundedButton.swift
> +
отступ

2024-05-15 06:15 UTC, SKemenov commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +        let authViewController = MistakesViewController(type: .oldVersion)
сделал

2024-05-15 06:15 UTC, SKemenov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +        self.alpha = 0.7
сделал приватный енам в классе

2024-05-15 06:16 UTC, SKemenov commented on DavaiPosmotrim/UI/RoundedButton.swift
> +
отступы поправил

2024-05-16 11:09 UTC, superaydumov approved these changes

2024-05-16 11:09 UTC, superaydumov commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +//        authCoordinator.start()
Вливать будем с закомментированным координатором авторизации?

2024-05-16 11:10 UTC, merged