Feature/karpunov/dp 24 edit main screen
DavayPosmotrim/dv-iOS pull request #25
Opened 2024-05-21 19:56 UTC by IuriiKarpunov

1. устранил конфликты констрейтов в MainViewControlle
2. сделал кнопками TableViewCell
3. добавил обновление имени

2024-05-23 10:31 UTC, superaydumov requested changes
Юра, привет! Хорошая работа
Сделал в MainViewController такую же реализацию наблюдателя за изменением.
Оставил свои мысли и комментарии.

2024-05-23 10:31 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainPresenter.swift
> +            return nil
На подумать:
Может лучше сделать так, чтобы функция возвращала пустую строку? Если будет ошибка, то у нас приложение закрашится, потому что nil получим.

2024-05-23 10:31 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        static let joinSessionViewController = "JoinSessionViewController"
Предлагаю перенести все строки в файл `Resources`

2024-05-23 10:31 UTC, superaydumov commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +    deinit {
deinit лучше переместить выше и расположить после `required init`

2024-05-23 11:55 UTC, IuriiKarpunov commented on DavaiPosmotrim/MainFlow/MainPresenter.swift
> +            return nil
Да, ты прав

2024-05-23 20:37 UTC, superaydumov approved these changes

2024-05-26 15:09 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +        presenter?.showNextScreen(screen: Resources.MainFlow.authViewController)
Юрий, я всё же за то, чтобы мы презентеру только говорили, что такая-то кнопка нажата, а он уже думал что делать дальше.
Тут вообще чуть не логично: экшн указывает на то, что нажата кнопка назад, а презентеру говорим покажи следующий экран.

2024-05-26 15:11 UTC, Sbat2000 commented on DavaiPosmotrim/MainFlow/MainViewController.swift
> +            presenter?.showNextScreen(screen: Resources.MainFlow.joinSessionViewController)
И тут тоже самое. Я считаю правильным презентеру просто сообщать что мы нажали что-то. Мы вью, мы не должны что-то решать. Мы должны сказать презентеру: пользователь нажал кнопку. Делай что-то с этим

2024-05-27 15:02 UTC, Sbat2000 approved these changes

2024-05-28 09:52 UTC, merged