feature/zimens/DP-3-loading-screen
DavayPosmotrim/dv-iOS pull request #30
Opened 2024-06-01 16:58 UTC by maxzim121

PR по выполненной задаче DP-3: создание экрана запуска приложения.
• Свёрстан launchScreen
• Создан SplashScreenViewController
• Добавлена анимация падения блоков с текстом по макету.
• Добавлена анимация перехода с экрана загрузки на основной экран приложения.
• Изменён файл SceneDelegate.

2024-06-02 10:24 UTC, superaydumov requested changes
Максим,  посмотрел наконец))
Вынес свои мысли в комментарии. Мне кажется, что нужно перейти всё на архитектуру MVP, а также добавить координатор для SplashFlow

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +import Foundation
Давай уберём этот импорт.
У тебя же ниже UIKit импортируется

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        tapView.backgroundColor = .clear
Предлагаю вынести эту строку для лейблов вот так:
```
[...].forEach {
$0.backgroundColor = .clear
}
```
Снизить повторяемость кода

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        let davayImageView = UIImageView(image: UIImage(named: "davayLabelImage"))
Можно избежать поиска картинки через строку, обращаясь напрямую к ассетам:
```
let davayImageView = UIImageView(image: UIImage.davayLabel)
```

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +
Предлагаю вынести переиспользуемый код, который есть в каждом лэйбле в приватный метод и использовать его уже внутри ленивого свойства:
```
private func sutupLabel(label: UILabel) {
label.textAllignment = .center
...
}
```

Так мы сильно сократим код и не будет повторяющихся строк))

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        thrillerLabel.text = "Триллер"
Строки лучше перенести в файл Resources. Мы их туда складываем
Создай свой enum SplashScreen и кидай всё в него

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        thrillerLabel.font = .systemFont(ofSize: 20)
Проверь пожалуйста шрифт в этих лэйблах. Мы по идее нигде не используем стандартный шрифт: у нас либо Inter, либо DaysOne 🤔

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        melodrammaLabel.backgroundColor = UIColor(named: "attentionAdditionalColor")
С цветами так же, как и с картинками.

Можно обращаться напрямую к ассетам в новой версии XCode: `UIColor.baseText`. В данном случае можно вообще просто `.baseText`

Слово color или image в конце автоматически опускается при генерации ассета.

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        view.backgroundColor = UIColor(named: "baseBackgroundColor")
Здесь можно просто `view.backgroundColor = .baseBackground`

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        ])
Можно создать массив с лэйблами на 281 строке например, а потом использовать его там, где надо)) не придётся дублировать массив

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +extension SplashScreenViewController: UIGestureRecognizerDelegate {}
Пустой экстеншен нужен в качестве заглушки?

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                              for: UIBezierPath(rect: self.davayImageView.frame))
Тут тоже строки, думаю, лучше перенасти в Resources

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +    }
Может перенесём этот метод в презентер (и заодно создадим его)?
Кажется, что расчёт как раз туда лучше

2024-06-02 10:24 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +            window.rootViewController = navigationController
Максим, думаю, что эту логику как раз перенести в координатор.
Мне видится это так: у нас стартует аппкоординатор, и он запускает SplashScreenFlow, а после сплэшскрина уже запускается онбординг и т.д.

2024-06-05 10:19 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +import Foundation
Убрал импорт

2024-06-05 10:20 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        tapView.backgroundColor = .clear
✅

2024-06-05 10:21 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        let davayImageView = UIImageView(image: UIImage(named: "davayLabelImage"))
✅

2024-06-05 10:21 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +
✅

2024-06-05 10:21 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        thrillerLabel.text = "Триллер"
✅

2024-06-05 10:22 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        thrillerLabel.font = .systemFont(ofSize: 20)
✅

2024-06-05 10:23 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        melodrammaLabel.backgroundColor = UIColor(named: "attentionAdditionalColor")
✅

2024-06-05 10:23 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        view.backgroundColor = UIColor(named: "baseBackgroundColor")
✅

2024-06-05 10:26 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        ])
✅

2024-06-05 10:31 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                              for: UIBezierPath(rect: self.davayImageView.frame))
✅

2024-06-05 10:32 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +extension SplashScreenViewController: UIGestureRecognizerDelegate {}
Да, перенес его на 12 строку
✅

2024-06-10 22:53 UTC, superaydumov approved these changes
Максим, молодец, что сократил код!)) Ставлю аппрув

Написал свои мысли по некоторым моментам, где хотелось бы немного изменить код

2024-06-10 22:53 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenCoordinator.swift
> +        navigationController.pushViewController(viewController, animated: true)
Возможно имеет смысл подумать над тем, чтобы поставить setViewControllers..но это для размышлений

2024-06-10 22:53 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        label.font = UIFont(name: "Inter-Regular", size: 20)
Шрифты у нас уже все занесены в файле UIFont+extension папки Helpers. Но этого размера почему-то не было во вкладке Typography в макете...странно. Занеси пожалуйста
Можешь использовать их так:
`label.font = UIFont.название шрифта`
или
`label.font = .название шрифта`

2024-06-10 22:53 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +    }
Всё-таки считаю, что лучше перенести этот метод в презентер)) для размышления

2024-06-10 22:53 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        }
Если переносится, то вот так:

[
   перенос на след. строку
].forEach {...}

2024-06-10 22:53 UTC, superaydumov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                  documentaryLabel]
Если переносится, то вот так:

[
перенос на след. строку
].forEach {...}

2024-06-13 10:17 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                  documentaryLabel]
✅

2024-06-16 12:18 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                                                   action: #selector(screenTapped(gestureRecognizer:)))
```swift
        let tapRecognizer = UITapGestureRecognizer(
            target: self,
            action: #selector(screenTapped(gestureRecognizer:))
        )
```
правильно переносить так

2024-06-16 12:18 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +            tapView.leftAnchor.constraint(equalTo: view.leftAnchor, constant: 0)
тут "constant: 0" точно нужен?

2024-06-16 12:18 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                                  for: UIBezierPath(rect: self.topView.frame))
аналогично
```swift
collision.addBoundary(
        withIdentifier: "topBorderIdent" as NSCopying,
        for: UIBezierPath(rect: self.topView.frame)
)
```

2024-06-16 12:18 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                              for: UIBezierPath(rect: self.davayImageView.frame))
аналогично, используй везде правильный перенос, если переносишь)

2024-06-19 12:55 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                                                   action: #selector(screenTapped(gestureRecognizer:)))
✅

2024-06-19 12:55 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +            tapView.leftAnchor.constraint(equalTo: view.leftAnchor, constant: 0)
✅

2024-06-19 12:55 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                                  for: UIBezierPath(rect: self.topView.frame))
✅

2024-06-19 12:55 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +                              for: UIBezierPath(rect: self.davayImageView.frame))
✅

2024-06-19 19:46 UTC, IuriiKarpunov approved these changes
Поправь что бы соответствовало кодстайлу, там немного) 
Ты молодец

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        var musicalLabel = UILabel(frame: CGRect(x: 200, y: -490, width: 119, height: 40))
когда у нас больше двух параметров пишем так:
var musicalLabel = UILabel(frame: CGRect(
x: 200, 
y: -490, 
width: 119, 
height: 40
))

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        var thrillerLabel = UILabel(frame: CGRect(x: 100, y: -445, width: 124, height: 40))
в этом месте аналогично

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        var melodrammaLabel = UILabel(frame: CGRect(x: 50, y: -400, width: 151, height: 40))
в этом месте аналогично

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        var melodrammaLabel = UILabel(frame: CGRect(x: 50, y: -400, width: 151, height: 40))
и так далее)

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +            $0.backgroundColor = .clear
[
leftView, 
rightView, 
bottomView, 
topView, 
backgroundView
].forEach {
            $0.backgroundColor = .clear
}

2024-06-19 19:46 UTC, IuriiKarpunov commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        [backgroundView, tapView].forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
[backgroundView, tapView].forEach { 
$0.translatesAutoresizingMaskIntoConstraints = false 
}

2024-06-21 13:52 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +            $0.backgroundColor = .clear
✅

2024-06-21 13:56 UTC, maxzim121 commented on DavaiPosmotrim/SplashScreen/SplashScreenViewController.swift
> +        [backgroundView, tapView].forEach { $0.translatesAutoresizingMaskIntoConstraints = false }
✅

2024-06-29 08:10 UTC, merged