[DP-27] - сделал CustomMovieSelection
DavayPosmotrim/dv-iOS pull request #36
Opened 2024-06-03 20:41 UTC by IuriiKarpunov

2024-06-19 16:14 UTC, SKemenov reviewed
Юра, хороший код и интересная анимация! 👍 
Мои вопросы и комментарии см. в пиарке

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +import UIKit
Один импорт лишний

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +    }
Строковые константы лучше перенести в `Resources`.
И сделать в виде `static let`, тогда не потребуется доставать rawValue

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +            imageBatton: "likeIcon"
Опечатка - batton

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +        }
А если presenter сделать не опциональным и уйти от использования fatalError? 
Мы в ините получаем презентер, какова вероятность, что его не будет?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +        guard currentIndex < selectionsMovie.count else { return nil }
Данная проверка не спасает от Fatal error: Index out of range

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +    }
Метод не берет на вход аргументы, 
Как вариант можно сделать `private (set) var currentMovieId: UUID?` и метод тогда становится не нужным

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +        self.currentMovieId = firstSelection?.id
Тут точно нужен self?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +    func getFirstMovie() -> SelectionMovieCellModel? {
Почему возвращаем опционал? Когда возможна такая ситуация, когда не будет первого фильма?
Почему не используешь `currentIndex`, ведь он вначале нулевой?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +    weak var coordinator: SelectionMoviesCoordinator?
`Presenter` ничего не знает про `view`,  которым управляет? 
Такое возможно, если часть бизнес логики осталась во вью и вью управляет процессом, а не презентер.

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +        currentIndex -= 1
ЧТо будет, если вызовется этот метод и `currentIndex` нулевой?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +            likedMovies.removeAll { $0 == id }
Хорошее решение! 👍

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +        view.backgroundColor = .white
Этот цвет не по Figma

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        label.textColor = .doneAdditional
В зависимости от величины оценки цвет рейтинга должен меняться, а у тебя он всегда зеленый

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +extension SelectionMoviesViewController: CustomMovieSelectionDelegate {
Предлагаю презентер сделать делегатом и управлять этими процессами

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        if percentage > 0 {
двойной  if ... if-else можно заменить на `switch`

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +//            heightAnchor.constraint(equalToConstant: 584),
закомментрированный код предлагаю убрать

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +            centralPaddingView.center = CGPoint(x: view.center.x + translation.x, y: view.center.y + translation.y / 2)
Чтобы вью не скакало перед анимацией, предлагаю тут к `view.center.y` добавить 16 (число актуально для стимулятора iPhone 15 Pro)

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +                    self.centralPaddingView.center = self.view.center
Чтобы вью не скакало после анимации, предлагаю тут к `view.center.y` добавить 16 (число актуально для стимулятора iPhone 15 Pro)

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +            centralPaddingView.center = CGPoint(x: view.center.x + translation.x, y: view.center.y + translation.y / 2)
Наверное неправильно харкодить отступ в коде. Лучше сделать расчет отступа исходя из высоты экрана для текущего девайса

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +                    self.centralPaddingView.center = self.view.center
Наверное неправильно харкодить отступ в коде. Лучше сделать расчет отступа исходя из высоты экрана для текущего девайса

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +    }
Вероятно этот метод должен быть в презентере. И уже оттуда управлять тем, что должна показать вью

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +    func animateSwipe(direction: CGFloat) {
Расчет данных для анимаций должен быть во вью или в презентере?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +extension SelectionMoviesViewController: CustomNavigationBarTwoButtonsDelegate {
Может сразу сам презентер сделать делегатом?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        view.backgroundColor = UIColor.white.withAlphaComponent(0.7)
По Figma у нас другой белый цвет

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        view.backgroundColor = UIColor.white.withAlphaComponent(0.7)
По Figma у нас другой белый цвет

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        view.backgroundColor = UIColor.white.withAlphaComponent(0.7)
Можно убрать этот вью совсем и изменять `.alpha` напрямую у кнопки?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        self.currentMovieId = model.id
self здесь точно нужен?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +    private func configureWithModel(model: SelectionMovieCellModel) {
Чтобы линтер не ругался на длину класса, приватные методы можно вынести в `private extension`

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        return CGSize(width: 343, height: remainingHeight)
А если экран девайса будет уже или намного шире `343`?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        let radius = view.bounds.width / 2.0
По Figma радиусы вроде все фиксированные, нет?

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        let genre = genresMovie[indexPath.row]
В данной коллекции у нас не строки, а элементы (по несколько элементов на строке), рекомендую использовать параметр `indexPath.item` чтобы не возникало путаницы

2024-06-19 16:14 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomNavigationBarTwoButtons.swift
> +    init(title: String, imageBatton: String) {
опечатка - Batton

2024-06-20 13:30 UTC, Sbat2000 commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesFactory.swift
> +    static func selectionMoviesViewController(
назови, пожалуйста, функцию как всегда такие называем: makeSelectionMoviesViewController - чтобы сразу было понятно, что она создает этот ВК.

2024-06-20 13:38 UTC, Sbat2000 commented on DavaiPosmotrim/Application/AppCoordinator.swift
>  }
Это не должно быть в апп координаторе. Надо посмотреть откуда мы запускаем данный флоу и потом туда перенести. Сейчас понятно, что мы делаем для того, чтобы посмотреть как работает, но надо не забыть все передалать может TODO написать?

2024-06-20 13:39 UTC, Sbat2000 commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +            showMainFlow()
Следовательно и это. Это будет в том координаторе, с которого мы будем запускать флоу.

2024-06-20 13:46 UTC, Sbat2000 commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +
я бы все же сделал так:
мы говорим презентеру, что нажата кнопка да или нет или еще что-то. 
Презентер уже думает что делать с это информацией, и говорит вью что показать.
ВЬю не отвечает за логику приложения, она у нас "глупая" она лишь может сказать презентеру, что пользователь сделал что-то, а презентер должен обработать это и сказать вью что делать дальше (или ничего не сказать)

2024-06-20 13:53 UTC, Sbat2000 requested changes
Юрий, большую работу проделал :) Спасибо!
Комментарии оставил в коде.
Также хочу выделить общий комментарий:
У нас View - довольно "глупая". Она может только отображать интерфейс и обрабатывать действия пользователя. То есть у нас должно быть так: Пользователь нажал кнопку, вью сообщило об этом презентеру, презентер обработал это и решил что делать дальше. Если надо что-то поменять на экране, он должен обратиться к вью и сказать ей напрямую: вью.поменяй цвет лэйбла в синий. При этом вью и презентер друг с другом обзаются через протоколы, у тебя есть протокол презентера и с ним все ок, надо добавить протокол вью. Ну и рассказать про вью перезнтеру. 
Все это делается для нескольких вещей:
1. Разделение отвественностей
2. Тестирование
3. Мы легко можем заменить вью на другое, главное чтобы оно соответствовало протоколу, также и с презентером.

2024-06-20 16:00 UTC, superaydumov commented on DavaiPosmotrim/Application/AppCoordinator.swift
>  }
Согласен с Сашей. Надо будет переносить многое в MainCoordinator

2024-06-20 16:03 UTC, superaydumov commented on DavaiPosmotrim/Helpers/UICollectionViewLayout+Extension.swift
> +    static func createLeftAlignedLayout(itemHeight: CGFloat) -> UICollectionViewLayout {
Я использовал этот элемент в своей переиспользуемой коллекции.
Если менять метод, то нужно заменить вызов везде по коду, где он используется

2024-06-20 16:05 UTC, superaydumov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMovieCellModel.swift
> +}
Могут ли у нас какие-либо свойства быть опциональными. Мне кажется стоит над этим подумать и хотя бы написать TODO, чтобы не упустить этот момент

2024-06-20 16:07 UTC, superaydumov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesCoordinator.swift
> +    }
Правильно ли, что эта метод у нас находится в данном координаторе?

2024-06-20 16:13 UTC, superaydumov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +    func showComeMovie() {
Я бы изменил неиминг метода на: `func showIncomingMovie()`

2024-06-20 16:17 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieCollectionCell.swift
> +    }
Для одного элемента лучше не использовать эту конструкцию.
Оставить все в методе настройки ячейки или в вычисляемом свойстве.

2024-06-20 16:20 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        label.numberOfLines = 0
А у нас в нем разве нет строк? Не очень понял почему 0

2024-06-20 16:22 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        button.setImage(UIImage(named: "inactiveNoSelectionIcon"), for: .normal)
можешь попробовать обратиться к картинке вот так:
`button.setImage(UIImage.inactiveNoSelectionIcon, for: .normal)`

2024-06-20 16:22 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        button.setImage(UIImage(named: "activeNoSelectionIcon"), for: .highlighted)
Аналогично))

2024-06-20 16:23 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        button.setImage(UIImage(named: "activeNoSelectionIcon"), for: .highlighted)
можешь попробовать обратиться к картинке вот так:
`button.setImage(UIImage.inactiveNoSelectionIcon, for: .normal)`
`button.setImage(UIImage.activeNoSelectionIcon, for: .normal)`

2024-06-20 16:23 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        button.setImage(UIImage(named: "activeRotateIcon"), for: .highlighted)
Аналогично))

2024-06-20 16:24 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        button.setImage(UIImage(named: "activeLikeIcon"), for: .highlighted)
Аналогично))

2024-06-20 16:24 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        noButton.setImage(UIImage(named: "activeNoSelectionIcon"), for: .normal)
Тут то же с картинкой))

2024-06-20 16:25 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        yesButton.setImage(UIImage(named: "activeLikeIcon"), for: .normal)
Тут то же с картинкой))

2024-06-20 16:25 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        }
Для одного элемента лучше эту конструкцию не использовать

2024-06-20 16:27 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        return CGSize(width: 343, height: remainingHeight)
Согласен. Хардкодить ширину лучше не стоит

2024-06-20 16:29 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomNavigationBarTwoButtons.swift
> +class CustomNavigationBarTwoButtons: UIView {
Просто для информации..попробую написать один кастомнный класс для навБара, чтобы использовать его один во всех случаях. Ну как и обсуждали вв общем))

2024-06-20 16:30 UTC, superaydumov reviewed
Юра, тоже посмотрел код!))
Оставил в комментах свои мысли по поводу улучшения

2024-06-20 17:13 UTC, IuriiKarpunov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        label.textColor = .doneAdditional
а где это прописано для этого рейтинга?

2024-06-20 17:21 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +        }
с presenter понятно, но массив может быть пустым selectionsMovie может быть пустым

2024-06-20 17:54 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +    }
я немного на распутье) 
Использование private(set) для свойства currentMovieId будет немного более эффективным с точки зрения производительности и кода, так как оно убирает ненужный метод и делает код чище. Это также соответствует рекомендациям Swift по использованию свойств(только прочитал). 
Поэтому наверно давай поменяем) согласен

2024-06-20 18:04 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +        }
дочитал след комментарии и понял, спасибо)

2024-06-20 18:09 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +        currentIndex -= 1
ничего, в методе canGetPreviousMovie() рассматриваются ситуации когда можно вернуться назад, а когда нет. например после мэтча мы не можем вернуться, два раза не можем вернуться и с индекс = 0

2024-06-20 18:22 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +extension SelectionMoviesViewController: CustomMovieSelectionDelegate {
если честно не очень понимаю необходимость, мне кажется это усложняет читаемость кода

2024-06-20 19:49 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +            centralPaddingView.center = CGPoint(x: view.center.x + translation.x, y: view.center.y + translation.y / 2)
справил, оказалось все намного проще, работает корректно и плавно

2024-06-20 19:52 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesViewController.swift
> +    func animateSwipe(direction: CGFloat) {
я считаю анимация должна быть во вью

2024-06-20 19:54 UTC, IuriiKarpunov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        view.backgroundColor = UIColor.white.withAlphaComponent(0.7)
с этим были проблемы, поэтому и пришлось к такому решению, оно оказалось популярным)

2024-06-20 20:06 UTC, IuriiKarpunov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        return CGSize(width: 343, height: remainingHeight)
frame.size.width. исправил)

2024-06-20 20:16 UTC, IuriiKarpunov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        let radius = view.bounds.width / 2.0
а он тут наверно и не нужен

2024-06-20 20:25 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesCoordinator.swift
> +    }
временное пока нет экрана

2024-06-20 20:26 UTC, IuriiKarpunov commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +        label.numberOfLines = 0
значит многострочный

2024-06-21 15:05 UTC, Sbat2000 approved these changes

2024-06-21 22:04 UTC, IuriiKarpunov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMovieCellModel.swift
> +}
модель будем менять когда увидим что на бэке будет)

2024-06-23 07:17 UTC, uistelmakh commented on DavaiPosmotrim/Application/AppCoordinator.swift
> +//            showMainFlow()
коммент убери

2024-06-23 07:20 UTC, uistelmakh commented on DavaiPosmotrim/UI/CustomMovieSelection/CustomMovieSelection.swift
> +//        label.textColor = .captionDarkText
тоже убери

2024-06-23 13:20 UTC, superaydumov approved these changes
Большую работу проделал!

2024-06-24 07:00 UTC, SKemenov approved these changes
Юра, мне нравится твой подход к код ревью, молодец, что можешь абстрагироваться и посмотреть на свой код под новым углом 👍

2024-06-24 07:00 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +    weak var coordinator: SelectionMoviesCoordinator?
👍

2024-06-24 07:00 UTC, SKemenov commented on DavaiPosmotrim/SelectionMoviesFlow/SelectionMoviesPresenter.swift
> +        currentIndex -= 1
Молодец, что это проверяешь 👍

2024-06-24 07:31 UTC, merged