Bugfix/karpunov/dp 38 create session coordinator logics
DavayPosmotrim/dv-iOS pull request #39
Opened 2024-06-09 15:24 UTC by IuriiKarpunov

1. Скорректировать логику выбора жанров и подборок — в зависимости от переключения на жанры или подборки должен обязательно быть сделан выбор для соответствующего экрана.
2. Добавить координатор — необходимо для навигации.
3. Добавил плавное появление уведомления

2024-06-10 10:47 UTC, Sbat2000 commented on DavaiPosmotrim/CreateSessionFlow/CreateSessionViewController.swift
> +        presenter.didTapNextButton(navigationController: navigationController)
Ура :)

2024-06-10 10:51 UTC, Sbat2000 commented on DavaiPosmotrim/CreateSessionFlow/CreateSessionViewController.swift
> +        presenter.didTapNextButton(navigationController: navigationController)
А теперь не ура :) Ты для чего то передаешь навконтроллер в презентер, но он есть в координаторе. Тебе надо в координаторе твоем создать метод показать показа экрана инвайта юзеров и просто сказать координатору из презентера:
coordinator?.showInviteUsersFlow()
а вот в координаторе уже собрать через фабрику юезр флоу (пока просто сделай метод, я его сам допишу, когда буду сливать ветку)

2024-06-10 10:52 UTC, Sbat2000 commented on DavaiPosmotrim/CreateSessionFlow/CreateSessionViewController.swift
> +        presenter?.backButtonTapped()
Ура :)

2024-06-10 10:55 UTC, Sbat2000 requested changes
Юрий, я написал в комментариях к коду.
Не надо передавать навконтроллер из вк в презентер. Презентер просто должен сказать координатору что показать, а у координатора уже есть навконтроллер.

2024-06-11 03:35 UTC, Sbat2000 approved these changes

2024-06-11 09:24 UTC, superaydumov reviewed
Хотел бы уточнить пару моментов..мне не очень понятна история с координатором. Как будет выглядеть координатор экрана приглашения пользователей?

2024-06-11 09:24 UTC, superaydumov commented on DavaiPosmotrim/CreateSessionFlow/CreateSessionCoordinator.swift
> +    }
А почему тут есть эта функция? По идее же она должна быть в координаторе, который относится в флоу приглашения пользователей, когда мы заканчиваем это флоу..

2024-06-11 09:24 UTC, superaydumov commented on DavaiPosmotrim/CreateSessionFlow/CreateSessionPresenter.swift
> +        coordinator?.showInvitingUsersFlow()
Нам, получается, не нужен координатор на флоу приглашения пользователей?

2024-06-11 09:24 UTC, superaydumov commented on DavaiPosmotrim/Protocols/CoordinatorProtocol.swift
> +    case createSession
По сути на 18 строчке есть уже это кейс)) Только называется немного иначе
Оставь какой-нибудь один

2024-06-11 10:55 UTC, superaydumov approved these changes
Убрал комменты по поводу координатора.
Оставил только с кейсом в протоколе

2024-06-12 08:55 UTC, merged