Feature/aidumov/dp 5 onboarding screen
DavayPosmotrim/dv-iOS pull request #9
Opened 2024-04-26 16:07 UTC by superaydumov

PR в соответствии с выполненной задачей DP-5 по добавлению онбординга пользователя при первом запуске приложения.
После прохождения онбординга пользователь перекидывается на AuthFlow (AuthViewController).

2024-04-29 08:36 UTC, SKemenov requested changes
Молодец, мне понравился код! 
Есть мелкие недочеты, просто нужно привыкнуть к новым правилам)

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    // MARK: - Computed proprties
В марках опечатка -> надо properties

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +        constraintsSetup()
Нейминг функций не по договоренности (см. readme.md)

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    // MARK: - Lifecycle
`// MARK: - Lifecycle` следует использовать для методов жизненного цикла VC - `viewDidLoad`, `ViewWillAppear` и тд.
Рекомендую тут использовать `// MARK: - Inits`

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +        }
Классно сделал!)

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +        }
Как вариант тут можно сделать тернарный оператор, например для leading констрейнта
```` swift
cellImageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: indexPath.row == 1 ? 0 : 32),

```

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    // MARK: - Computed properties
Тут не совсем корректный марк. Это lazy view, они высчитываются один раз при первом обращении. Computed properties - каждый раз высчитывается при обращении к ним.

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +            forCellWithReuseIdentifier: OnboardingCollectionViewCell.reuseIdentifier)
Не по договоренностям (readme.md -> Перенос скобок)
Если параметры функции с новой строки, то закрывающую скобку рекомендуется перенести на новую строку.

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    // MARK: - Lifecycle
аналогично, тут лучше марк inits

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    // MARK: - Private methods
Как вариант - все private methods можно вынести в `private extension OnboardingViewController { }`

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +        toogleButtons()
Нейминг функций не по правилам

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    private func toogleButtons() {
опечатка - нужно toggleButtons

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +        return pages.count
тут ключевое слово `return` можно опускать

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +}
неиспользуемый код. Рекомендую удалить. Протокол кстати тоже пустой. Какое его назначение?

2024-04-29 08:36 UTC, SKemenov commented on DavaiPosmotrim/UI/CustomButtons.swift
> +final class CustomButtons: UIView {
См. комментарии к предыдущим файлам

2024-04-30 15:23 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    // MARK: - Lifecycle
Done

2024-04-30 15:23 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +        constraintsSetup()
Done

2024-04-30 15:23 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    // MARK: - Computed proprties
Done

2024-04-30 15:29 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +        }
Хорошая идея! Переписал с учетом комментария

2024-04-30 15:38 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    // MARK: - Computed properties
Заменил на Lazy Properties. Хотя, честно говоря, особенной разницы не вижу
Потому что они всё равно высчитываются..хоть и один раз))

2024-04-30 15:39 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +            forCellWithReuseIdentifier: OnboardingCollectionViewCell.reuseIdentifier)
Done

2024-04-30 15:41 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    // MARK: - Lifecycle
Done

2024-04-30 15:41 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +        toogleButtons()
Поправил

2024-04-30 15:41 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +    private func toogleButtons() {
Done

2024-04-30 15:45 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +}
Насколько я понял, это протокол вьюконтроллера, с помощью которого он связывается с презентером для вызовы необходимых методов.
Добавил марк, чтобы не забыть добавить код, если понадобится.

2024-04-30 15:47 UTC, superaydumov commented on DavaiPosmotrim/UI/CustomButtons.swift
> +final class CustomButtons: UIView {
Done

2024-04-30 17:42 UTC, IuriiKarpunov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +
Лишний перенос строки

2024-04-30 17:43 UTC, IuriiKarpunov approved these changes

2024-04-30 18:40 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +
Done

2024-05-01 07:30 UTC, SKemenov approved these changes
Супер!

2024-05-01 07:32 UTC, SKemenov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +}
ок

2024-05-01 10:40 UTC, uistelmakh commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +        UserDefaults.standard.setValue(true, forKey: "isOnboardingShown")
В константы вынести

2024-05-01 10:47 UTC, uistelmakh commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    static let reuseIdentifier = "OnboardingCollectionViewCell"
Создай Енам с константами

2024-05-01 10:58 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingViewController.swift
> +        UserDefaults.standard.setValue(true, forKey: "isOnboardingShown")
Done

2024-05-01 11:03 UTC, superaydumov commented on DavaiPosmotrim/OnboardingViewController/OnboardingCollectionViewCell.swift
> +    static let reuseIdentifier = "OnboardingCollectionViewCell"
Done

2024-05-01 11:08 UTC, merged